PerfectFit-project/virtual-coach-rasa

- onboarding/README.md
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/187
> Change onboarding readme for windows

- Rasa_Bot/actions/actions.py
- Rasa_Bot/config.yml
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
Fixes #[https://github.com/PerfectFit-project/virtual-coach-issues/issues/178](url)
> See myself

- Rasa_Bot/actions/actions.py
- Rasa_Bot/config.yml
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
- Rasa_Bot/tests/test_actions.py
Merge from Makeda and Nele branches, action test- rewritten.
> Ask for more words if not enough, (with action-test) in future self dialog

- .prospector.yml
- Rasa_Bot/actions/actions.py
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
Fixes #https://github.com/PerfectFit-project/virtual-coach-issues/issues/179
> Rescheduling dialog

- scheduler/celery_tasks.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/213
> Schedule trigger_ask_foreseen_hrs for every hour

- Rasa_Bot/actions/.env-example
- Rasa_Bot/actions/actions.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/rules.yml
- Rasa_Bot/domain.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/20
> Get cigarettes from tracker

- Rasa_Bot/domain.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/199
> Fix slot mappings

- Rasa_Bot/Dockerfile-macos-m1
- Rasa_Bot/README.md
- Rasa_Bot/actions/Dockerfile
- Rasa_Bot/requirements.txt
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/191
> Bump rasa version to 3.1.0

- Rasa_Bot/actions/actions.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
Fixes the first element of https://github.com/PerfectFit-project/virtual-coach-issues/issues/224, i.e., rescheduling options depend on the current time and there is a 4th rescheduling option for 1h from now.
> Resched options

- Rasa_Bot/actions/actions.py
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
> Store i see myself as answers in db

- .env-example
- scheduler/celery_tasks.py
Part of https://github.com/PerfectFit-project/virtual-coach-issues/issues/238
This makes the scheduler use the REDIS_URL env var, to make integration with Heroku's managed redis work
> Use REDIS_URL in scheduler

- Rasa_Bot/actions/actions.py
- Rasa_Bot/actions/requirements-actions.txt
last component that fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/219. There is a separate pull request for the main to update the tests.
> Timezone rasa actions

- Rasa_Bot/actions/actions.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/181.
Uses conditional response variations.
> Future self rep

- Rasa_Bot/actions/actions.py
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/rules.yml
- Rasa_Bot/domain.yml
rasa action and conversation for https://github.com/PerfectFit-project/virtual-coach-issues/issues/170
> set tracker reminder

- Rasa_Bot/actions/actions.py
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/stories.yml
- Rasa_Bot/domain.yml
- Rasa_Bot/requirements.txt
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/254 (tasks 2 and 3).
> Get first aid kit

- Rasa_Bot/actions/actions.py
- Rasa_Bot/actions/actions_minimum_functional_product.py
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/stories_minimum_functional_product.yml
- Rasa_Bot/domain.yml
- Rasa_Bot/domain/domain_minimum_functional_product.yml
fixes #212
https://github.com/PerfectFit-project/virtual-coach-issues/issues/212
> Remove pa dialog 2

- Rasa_Bot/actions/actions_common.py
- Rasa_Bot/actions/actions_execution_dialogs.py
- Rasa_Bot/actions/actions_future_self_dialog.py
- Rasa_Bot/actions/actions_preparation_dialogs.py
- Rasa_Bot/actions/actions_rescheduling_dialog.py
- Rasa_Bot/actions/definitions.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/stories_execution_dialogs.yml
- Rasa_Bot/data/stories_future_self_dialog.yml
- Rasa_Bot/data/stories_rescheduling_dialog.yml
- Rasa_Bot/domain/domain_common.yml
- Rasa_Bot/domain/domain_execution_dialogs.yml
- Rasa_Bot/domain/domain_future_self_dialog.yml
- Rasa_Bot/domain/domain_preparation_dialogs.yml
- Rasa_Bot/domain/domain_rescheduling_dialog.yml
- scheduler/celery_tasks.py
- scheduler/requirements.txt
- scheduler/utils.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/210
> Trigger reschedule future self

- Rasa_Bot/actions/actions_preparation_dialogs.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/data/rules.yml
- Rasa_Bot/domain/domain_preparation_dialogs.yml
Made an additional branch on top of the previous one so just need to merge it back
> Simple pull into my own branch

- Rasa_Bot/actions/actions_future_self_dialog.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/credentials.yml
- Rasa_Bot/custom_channels.py
- requirements-dev.txt
- scheduler/README.md
- scheduler/celery_tasks.py
- scheduler/requirements.txt
Fixed the external triggering by including two input channels, one for the triggering and one for the regular conversation flow. Each input channel has a corresponding output channel and they function as intended.
> External Triggering

- Rasa_Bot/Dockerfile
- Rasa_Bot/actions/actions_future_self_dialog.py
- Rasa_Bot/actions/actions_general_activity.py
- Rasa_Bot/actions/definitions.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/actions/validator.py
- Rasa_Bot/data/stories_general_activity.yml
- Rasa_Bot/domain/domain_general_activity.yml
- Rasa_Bot/domain/domain_generic.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/306.
Together with corresponding pull request for virtual-coach-main for the e2e testing.
> Persusasion

- Rasa_Bot/actions/actions_preparation_phase.py
- Rasa_Bot/data/rules_preparation_phase.yml
- Rasa_Bot/domain/domain_preparation_phase.yml
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/313
Added the preparation phase dialog
> 313 preparation phase dialog

- Rasa_Bot/actions/actions_preparation_dialogs.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/requirements.txt
- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/336 
The issue was due to dependencies
> fixing requirements file

- Rasa_Bot/actions/actions_idle_commands.py
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/rules/rules.yml
- Rasa_Bot/data/rules/rules_idle_commands.yml
- Rasa_Bot/domain/domain_common.yml
- Rasa_Bot/domain/domain_generic.yml
- Rasa_Bot/domain/domain_idle_commands.yml
Fix: https://github.com/PerfectFit-project/virtual-coach-issues/issues/321
> 321 implement list of commands

- Rasa_Bot/actions/actions_weekly_reflection.py
- Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/350.
Weekly reflection dialog is divided into 6 parts for this.
> 350 restart weekly reflection

- Rasa_Bot/actions/actions_goal_setting_dialog.py
- Rasa_Bot/domain/domain_goal_setting_dialogs.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/341 using conditional response variations.
> 341 goal imp

- Rasa_Bot/actions/actions_notifications.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/requirements.txt
- onboarding/requirements.txt
- scheduler/celery_tasks.py
- scheduler/celery_utils.py
- scheduler/requirements.txt
- scheduler/state_machine/const.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/91
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/248
Celery checks programmatically if a new connection request has been sent to the therapist. In case a new request is found and the user is not yet registered in the DB, the request is accepted. Upon the request acceptance, the needed information are stored in the DB and the intervention is started.
> 248 oboarding

- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/rules/rules_notifications.yml
- Rasa_Bot/requirements.txt
- scheduler/celery_tasks.py
- scheduler/celery_utils.py
- scheduler/state_machine/const.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/368
> 368 send inactive notification

- Rasa_Bot/domain/domain_profile_creation.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/359.
Also added a "gaat" in an utterance earlier in the profile creation dialog.
Timing was not an issue for me.
> add per week to godin questions

- scheduler/celery_tasks.py
Correcting the date format error in the scheduling of the periodic `notify_new_day` task
> Hotfix notify date

- Rasa_Bot/domain/domain_goal_setting_dialogs.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/371
> 371 fix date format goal setting

- scheduler/celery_tasks.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/379
> modified task arguments and call

- scheduler/state_machine/controller.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/378
> added delay after long dialogs

- Rasa_Bot/actions/actions_common.py
- Rasa_Bot/actions/actions_first_aid_kit.py
- Rasa_Bot/actions/actions_general_activity.py
- Rasa_Bot/actions/actions_idle_commands.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/rules/rules_idle_commands.yml
- Rasa_Bot/domain/domain_common.yml
- Rasa_Bot/domain/domain_first_aid_kit.yml
- Rasa_Bot/domain/domain_idle_commands.yml
- onboarding/requirements.txt
- scheduler/celery_tasks.py
- scheduler/requirements.txt
- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/377
> 377 revirew fak

- scheduler/celery_utils.py
- scheduler/state_machine/state.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/370
> Exclude fsm of user who completed the intervention

- Rasa_Bot/actions/actions_watching_a_video.py
- Rasa_Bot/data/rules/rules_profile_creation.yml
- Rasa_Bot/data/rules/rules_set_video_links.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/386
> switch intro sentence

- Rasa_Bot/actions/actions_general_activity.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/374
> check if effor slot is not none

- Rasa_Bot/actions/actions_relapse_dialogs.py
- Rasa_Bot/data/rules/rules_relapse_dialog.yml
- Rasa_Bot/domain/domain_generic.yml
- Rasa_Bot/domain/domain_relapse_dialogs.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/389
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/21 issues 1, 2, 3, 4 and the smiley comment from Eline below.
> 389 hrs pa

- Rasa_Bot/data/rules/rules_watching_a_video.yml
- Rasa_Bot/domain/domain_watching_a_video.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/394, which is based on https://github.com/PerfectFit-project/testing-tickets/issues/20.
Also fixed the sentence ‘Je komt daarna weer terug in de app’ based on Eline's suggestion in the same testing issue.
> fix formulations video watching dialog

- Rasa_Bot/actions/requirements-actions.txt
- onboarding/requirements.txt
- scheduler/requirements.txt
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/409.
Update db version after updating resource texts in db.
> update db version

- Rasa_Bot/domain/domain_profile_creation.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/399
> Fix spelling error

- Rasa_Bot/data/rules/rules_set_video_links.yml
- Rasa_Bot/domain/domain_profile_creation.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/397
The second message was delayed (yes, the usual imposed delay...) and the following action, which was the triggering of the video dialog was too fast. Merging the first and the second message is the fastest and simplest solution. More complicated things can be done, but I would definitely not go that way.
> merged first two utterances

- Rasa_Bot/actions/actions_general_activity.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/401
> added quotation marks to activity titles

- Rasa_Bot/domain/domain_goal_setting_dialogs.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/419
> Remove duplicated instructions

- Rasa_Bot/data/rules/rules_goal_setting_dialog.yml
- Rasa_Bot/data/rules/rules_relapse_dialog.yml
- Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
- Rasa_Bot/domain/domain_closing_dialog.yml
- Rasa_Bot/domain/domain_first_aid_kit.yml
- Rasa_Bot/domain/domain_goal_setting_dialogs.yml
- Rasa_Bot/domain/domain_preparation_phase.yml
- Rasa_Bot/domain/domain_relapse_dialogs.yml
- Rasa_Bot/domain/domain_rescheduling_dialog.yml
- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/406.
Made changes to the dialog endings as indicated by Anke.
> made closing modifications to dialogs from Anke

- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/425
> removed wrong formulation

- Rasa_Bot/actions/actions_notifications.py
- Rasa_Bot/actions/definitions.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/rules/rules_goal_setting_dialog.yml
- Rasa_Bot/data/rules/rules_notifications.yml
- Rasa_Bot/domain/domain_notifications.yml
- onboarding/requirements.txt
- scheduler/requirements.txt
- sensor_api/sensorapi/connector.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/381
> 381 add reminder to wear watch

- Rasa_Bot/actions/actions_relapse_dialogs.py
- Rasa_Bot/actions/requirements-actions.txt
- Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
- Rasa_Bot/domain/domain_generic.yml
- Rasa_Bot/domain/domain_relapse_dialogs.yml
- onboarding/requirements.txt
- scheduler/requirements.txt
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/422
- Corrected the validation of `how_feel_smoke` and `hrs_feeling_slot` in relapse dialog.
- Added the graph visualization in missing points.
- Updated dependencies to the latest DB version
> 422 correction weekly reflection

- Rasa_Bot/actions/helper.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/424
> Change make step overview function to dutch

- Rasa_Bot/domain/domain_general_activity.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/413.
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/56
Simple way of adding many conditions (looks ugly but unlikely to lead to errors).
> add conditional response variations

- requirements-dev.txt
- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/436
Upon the completion of the medication talk dialog in the preparation phase, check whether the next dialog and the notifications have to be planned or not.
> 436 check track behavior trigger

- scheduler/celery_tasks.py
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/68
> correct morning time

- Rasa_Bot/domain/domain_profile_creation.yml
- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/430.
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/442.
Did not retrain since the changes were so small.
> typo and reformulation

- Rasa_Bot/actions/helper.py
fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/433
> Add orange color to step bar graph

- Rasa_Bot/actions/actions_relapse_dialogs.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/config.yml
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/rules/rules_closing_dialog.yml
- Rasa_Bot/data/rules/rules_relapse_dialog.yml
- Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
- Rasa_Bot/domain/domain_relapse_dialogs.yml
- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/445
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/66 (corresponding testing ticket)
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/428
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/65 (corresponding testing ticket)
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/455
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/76 (corresponding testing ticket)
- Added sentence that Eline asked to add in weekly reflection dialog
- Added conditional response variations checking if one of the HRS graphs is empty in the weekly reflection dialog.
- For the smoking HRS situations figure, the figure is not shown when it is empty. …
> added sentence from Eline in weekly reflection dialog

- scheduler/state_machine/controller.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/449
As the notification is immediately consumed (not planned for the future), it doesn't need to be stored in the DB. The  intent has been changed to match the logic of the other immediately consumed notifications, such as the notification for inactivity.
> notification immediately consumed not stored in db

- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/456
See: https://github.com/PerfectFit-project/testing-tickets/issues/62
> Add text about keeping intensity goal

- Rasa_Bot/actions/actions_notifications.py
- Rasa_Bot/data/rules/rules_notifications.yml
- Rasa_Bot/domain/domain_notifications.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/435
> 435 add number steps yesterday notification

- Rasa_Bot/actions/actions_closing_dialog.py
- Rasa_Bot/actions/helper.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/462
- get tracked cigarettes from NiceDay
- get reported cigarettes from (re)lapses
- check smoking status in closing dialog
> 462 get smoking status

- Rasa_Bot/README.md
- scheduler/state_machine/state_machine_utils.py
- sensor_api/sensorapi/connector.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/461
- Moved the URLs definition to .env file
- Updated the prod URL
> moved api url to env

- Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
- sensor_api/sensorapi/connector.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/466
> Change step algorithm, use 0 instead of average

- Rasa_Bot/actions/actions_closing_dialog.py
- Rasa_Bot/actions/actions_goal_setting_dialog.py
- Rasa_Bot/actions/actions_idle_commands.py
- Rasa_Bot/data/nlu.yml
- Rasa_Bot/data/rules/rules_idle_commands.yml
- Rasa_Bot/domain/domain_common.yml
- Rasa_Bot/domain/domain_idle_commands.yml
- Rasa_Bot/tests/test_conversations.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/434
@wbaccinelli note, I did not test this yet.
> 434 step goal command

- Rasa_Bot/actions/actions_idle_commands.py
- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/470
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/87
- The fsm goes directly to the execution state in case the quit date has been reached, even if the first aid kit video has not been completed
- Save the status when running it, to make sure that the correct state has been stored
> 470 fak video non mandatory

- Rasa_Bot/actions/actions_closing_dialog.py
- Rasa_Bot/actions/actions_first_aid_kit.py
- Rasa_Bot/actions/actions_future_self_dialog.py
- Rasa_Bot/actions/actions_general_activity.py
- Rasa_Bot/actions/actions_goal_setting_dialog.py
- Rasa_Bot/actions/actions_minimum_functional_product.py
- Rasa_Bot/actions/actions_relapse_dialogs.py
- Rasa_Bot/actions/helper.py
- Rasa_Bot/actions/requirements-actions.txt
- onboarding/requirements.txt
- scheduler/celery_tasks.py
- scheduler/celery_utils.py
- scheduler/requirements.txt
- scheduler/state_machine/state_machine_utils.py
Closing all the sessions in scheduler and rasa_actions
> Fix managed db

- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/474
> check completion state of 29 activity

- Rasa_Bot/actions/actions_notifications.py
- Rasa_Bot/domain/domain_notifications.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/475
> 475 notification open senseeact

- scheduler/state_machine/state_machine_utils.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/476
> fixing days

- Rasa_Bot/actions/actions_notifications.py
- Rasa_Bot/domain/domain_notifications.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/478
> 478 change notification no data

- sensor_api/sensorapi/connector.py
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/479
> Add max value to intensity goal

- Rasa_Bot/actions/actions_weekly_reflection.py
- scheduler/state_machine/controller.py
- scheduler/state_machine/state_machine_utils.py
Two changes made:
- Verder implementation changed to prefer other dialogues over general activity
- New day changed to run uncompleted general activity rather than storing a new one
> General activity restart dialog

- Rasa_Bot/actions/helper.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/486
The issue was that we were not copying over the closed_answers_id so it was always none
> fix: empty graphs fix

- Rasa_Bot/actions/actions_weekly_reflection.py
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/488
changed the check
> fix: check execution week 12 instead of 11

- Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
Fix https://github.com/PerfectFit-project/virtual-coach-issues/issues/490
> fix: set slot before week number check in weekly reflection

- Rasa_Bot/actions/actions_goal_setting_dialog.py
only save to db if we are in goal setting dialog.
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/491
> add if check

- Rasa_Bot/data/rules/rules_notifications.yml
- Rasa_Bot/domain/domain_notifications.yml
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/495
> 495 reminder open senseeact
