Rasa_Bot/config.yml

TED policy training already converges to near 100% accuracy after 30/40 epochs. With 50 epochs we are save. This saves a lot of time when training rasa core.

Less epochs for training TED

---

Rasa_Bot/Dockerfile

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/217 for now.
Problem was that the permissions did not allow the tracker store to be created on Windows. There is a follow-up issue to revert these extensive new permissions later (https://github.com/PerfectFit-project/virtual-coach-issues/issues/216).

Trackerstore permissions

---

Rasa_Bot/custom_channels.py

This fixes the following pylint complaints:
https://github.com/PerfectFit-project/virtual-coach-rasa/runs/5752897704?check_suite_focus=true
The problem was that in  the parent class `InputChannel` has `name` as a classmethod, and the child class implemented them as a normal method.

Make Channel.name classmethod

---

.env-example
Rasa_Bot/README.md
Rasa_Bot/actions/.env-example
Rasa_Bot/actions/actions.py
Rasa_Bot/docker-compose.yml
scheduler/celery_tasks.py

As part of issue https://github.com/PerfectFit-project/virtual-coach-issues/issues/236 , this makes the Rasa actions scripts use the `DATABASE_URL` env instead of DB_HOST.

Issue236 use database url

---

Rasa_Bot/actions/actions_common.py
Rasa_Bot/actions/actions_execution_dialogs.py
Rasa_Bot/actions/actions_preparation_dialogs.py
Rasa_Bot/actions/requirements-actions.txt
Rasa_Bot/data/stories_execution_dialogs.yml
Rasa_Bot/domain/domain_common.yml
Rasa_Bot/domain/domain_execution_dialogs.yml
Rasa_Bot/domain/domain_preparation_dialogs.yml
scheduler/celery_tasks.py
scheduler/requirements.txt
scheduler/utils.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/252

252 create execution phase dialogs

---

Rasa_Bot/actions/actions_preparation_dialogs.py
Rasa_Bot/actions/helper.py
Rasa_Bot/data/nlu.yml
Rasa_Bot/data/rules.yml
Rasa_Bot/domain/domain_preparation_dialogs.yml
Rasa_Bot/story_graph.dot

Added functionality to trigger a form by typing in 'user preferences'. The form will ask for the users preferences and validate each input, and will subsequently store the preferences in the database. 
In order to test this functionality the .env file in the main repo needs to be changed so that the TEST_USER_ID is the ID of the device that is being tested from.

Storing User Preferences in DB

---

Rasa_Bot/actions/actions_first_aid_kit.py
Rasa_Bot/actions/definitions.py
Rasa_Bot/actions/requirements-actions.txt

Changed the rasa_action to retrieve the first aid kit, in order to get only the 5 activities with the highest rating

get five highest rated activities

---

Rasa_Bot/Dockerfile
Rasa_Bot/actions/actions_first_aid_kit.py
Rasa_Bot/actions/actions_general_activity.py
Rasa_Bot/actions/helper.py
Rasa_Bot/actions/requirements-actions.txt
Rasa_Bot/data/rules/rules_first_aid_kit.yml
Rasa_Bot/domain/domain_first_aid_kit.yml
onboarding/requirements.txt
scheduler/requirements.txt

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/318

Revise first aid kit

---

scheduler/celery_tasks.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/344

changed dialog checking and new day to periodic tasks

---

Rasa_Bot/actions/actions_notifications.py
Rasa_Bot/actions/definitions.py
Rasa_Bot/actions/helper.py
Rasa_Bot/actions/requirements-actions.txt

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/357

357 query steps

---

Rasa_Bot/actions/actions_weekly_reflection.py
Rasa_Bot/actions/requirements-actions.txt
Rasa_Bot/domain/domain_weekly_reflection_dialog.yml
Rasa_Bot/requirements.txt

fix: https://github.com/PerfectFit-project/virtual-coach-issues/issues/351
fix: https://github.com/PerfectFit-project/testing-tickets/issues/9

351 type klaar statement

---

Rasa_Bot/actions/actions_closing_dialog.py
Rasa_Bot/data/rules/rules_closing_dialog.yml
Rasa_Bot/domain/domain_closing_dialog.yml

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/363
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/12

363 fix closing dialog

---

Rasa_Bot/custom_channels.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/360 
The messages sending thorough the API happens when the dialogs are externally triggered. The response is sent to the API through the `custom_channels.py`. A delay between one message and the other has been added there.

adjusted speed to message length

---

Rasa_Bot/domain/domain_notifications.yml

Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/13
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/364

364 adapt text notification

---

Rasa_Bot/README.md

Partially fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/221. 
Lists sources used throughout the dialogs and included algorithms.
Does not include sources of content in database. Will include that later in the database repo.

221 sources rasa

---

scheduler/celery_tasks.py

First temporary fix by increasing the [`visibility_timeout`](https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html#id1)

Increasing visibility timeout

---

Rasa_Bot/actions/helper.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/384
Note that it can still happen that the text for the actual steps and step goal can overlap, in case the number of steps and goal is around 3000... Check the before and after image in the issue: https://github.com/PerfectFit-project/virtual-coach-issues/issues/384

Enhance plot of figure with steps and step goals

---

scheduler/celery_tasks.py
scheduler/state_machine/const.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/382

fixing everything

---

Rasa_Bot/actions/actions_preparation_phase.py
Rasa_Bot/actions/actions_watching_a_video.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/388
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/391
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/22
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/23
The problem was that the type of task that was sent to the scheduler by the video dialogs was wrong. What happened was that the just the generic `watch_video_dialog` and `reschedule_preparation_phase` dialogs where stored in the FSM. If the dialog expired, and the FSM rescheduled it, the wrong element was saved in the DB, and it was never marked as completed.

changed celery task in the actions

---

scheduler/celery_tasks.py
scheduler/state_machine/const.py
scheduler/state_machine/controller.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/390
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/19
After the completion of the profile creation dialog, the conversation is now paused for 30 seconds before triggering the next dialog. The pause is necessary for two reasons: 
- we cannot triggered immediately the next dialog, because the messages of the profile will be dispatched also during the new dialog (due to the time delay used between the messages)
- if the user types something during between the two dialogs, mixed messages will be received

390 pause after profile creation

---

scheduler/celery_tasks.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/398
The 'verder' command was received. It triggered the dialog correctly, but for the dialogs where the rescheduling was used, the first thing that happened was that rasa requested the 'rescheduling dialog' to be triggered. As the dialog was seen already as running, the scheduler did not execute this.
This check is actually needed just for the notifications, so it has been moved there.

Fixing the verder problem

---

Rasa_Bot/actions/actions_first_aid_kit.py
Rasa_Bot/actions/actions_relapse_dialogs.py
Rasa_Bot/data/rules/rules_relapse_dialog.yml
Rasa_Bot/domain/domain_relapse_dialogs.yml
scheduler/celery_tasks.py
scheduler/state_machine/const.py
scheduler/state_machine/controller.py
scheduler/state_machine/state.py
scheduler/state_machine/state_machine.py
scheduler/state_machine/state_machine_utils.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/396
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/25
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/393
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/26
- Storing the branch chosen by the user in the relapse dialog as a new closed answer
- Moved the expiration case management from the celery_tsks to the single state for clarity
- Improved intents management in ehbo 
- In the relapse state, the dialog is auto-completed in case a user-initiated relapse dialog expires, out of the relapse branch

396 hrs autocomplete on expire

---

Rasa_Bot/actions/actions_rescheduling_dialog.py
Rasa_Bot/actions/definitions.py
scheduler/celery_tasks.py
scheduler/state_machine/const.py
scheduler/state_machine/state_machine_utils.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/392
Fixes: https://github.com/PerfectFit-project/testing-tickets/issues/24
- Check for the time before scheduling and before triggering a scheduled task. If the task occurs in nighttime, it is moved to the next morning 
- Avoid checking for the dialog status in the night.

Avoid messages in the night

---

scheduler/state_machine/controller.py
scheduler/state_machine/state_machine_utils.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/415
Check if the conditions for running the weekly reflection dialog are met ager the completion of the GA dialog in the execution phase. The conditions come from the [intervention timings](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B1B69D6E4-49AA-438A-B3F2-602CEDBBFF9E%7D&file=2022.10.10_Perfect%20Fit%20app%20bible%20(Content%20overview%20and%20planning).xlsx&action=default&mobileredirect=true) and they are meant to distinguish a user-triggered GA dialog from a planned one.

415 correct weekly reflection triggering

---

Rasa_Bot/actions/actions_execution_dialogs.py
Rasa_Bot/actions/actions_relapse_dialogs.py
Rasa_Bot/data/rules/rules_relapse_dialog.yml
Rasa_Bot/domain/domain_relapse_dialogs.yml

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/408
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/53
- Moved possibility to leave the dialog in the first question.
- Added `current_intervention_component` slot setting for correctly marking the dialog completion.
- Added a final sentence in case the user leaves the dialog in the first question.

408 exit relapse dialog

---

Rasa_Bot/actions/actions_watching_a_video.py
Rasa_Bot/actions/definitions.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/405

fixed video waiting time

---

scheduler/state_machine/controller.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/417
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/412
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/44
- The goal setting dialog is triggered on the expected date, even if the short version of the future self has not been completed.
- If the date for showing the short version of the future self video has expired, it is not shown. As this is checked when the long version has been completed, we avoid a repetition of the same content.

start the goal setting state if the tracking time is over

---

scheduler/state_machine/controller.py
scheduler/state_machine/state_machine_utils.py

- First general activity dialog (and consequent weekly reflection) now scheduled in the preferred time also on week 1, instead of triggering it right after the introduction video (sent on the quit date).
- Corrected the scheduling time, to make use of the actual preferred time set by the user.
- Completion of the short version of the future self dialog not mandatory for scheduling the next general activity dialog.
Also fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/429

reviewed logic for scheduling weekly reflections dialog

---

requirements-dev.txt
scheduler/state_machine/controller.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/444
In order to avoid the messages of two consecutive dialogs to overlap in the execution phase: 
- Added a delay between the end of the weekly reflection and the beginning of the future self video.
- Added a delay between the end of the general activity dialog  and the beginning of the weekly reflection.

444 delay trigger fs

---

scheduler/state_machine/controller.py
scheduler/state_machine/state_machine_utils.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/459
The tracking duration was computed from the first day of the preparation, but it actually starts after the tracking behavior dialog has been completed. This has been changed by checking the completion time of the dialog.
Also, the need of administering the general activity dialog is now checked before moving the the goal setting.

fixed the logic for checking the duraiton of the tracking state

---

scheduler/state_machine/controller.py
scheduler/state_machine/state_machine_utils.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/452
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/73
- Added the missing notifications between the quit date and the first general activity
- Default PA group to 1 in case no PA group has been set
- Grouped redundant code in a single function to schedule the PA notifications

452 missing step goal notification

---

sensor_api/sensorapi/connector.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/460
What was going wrong: if there was no data from 9 days where the step goal should have been calculated, a NaN value was rounded, which gave the error. 
Fixed by checking if the data is empty or not, if empty, the goal is directly set to the minimum value.

Fix case no data available for step goal calculation

---

Rasa_Bot/actions/actions_weekly_reflection.py
Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml
Rasa_Bot/domain/domain_watching_a_video.yml
Rasa_Bot/domain/domain_weekly_reflection_dialog.yml

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/464.
Fixes https://github.com/PerfectFit-project/testing-tickets/issues/81 (corresponding testing issue.)
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/467
- Split form introduction sentence to remove the part about taking time so that it is not repeated when the form is not filled successfully.
- Removed the extra klaar utterance as part of the form validation.
- Fixed typo in video watching dialog.

split utterance, remove klaar from form validation, retrain

---

Rasa_Bot/domain/domain_common.yml

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/468.
Changed the formulation for the message sent when the help functionality is not available.

changed formulation help not available message

---

Rasa_Bot/actions/helper.py

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/480

removed and changed incorrect query params

---

scheduler/state_machine/controller.py
scheduler/state_machine/state_machine_utils.py

Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/482
During the execution phase, every day the the state machine checks if the weekly reflection dialog has been planned for the current week. It retrieves the last date when the weekly reflection should have been sent and, if no new weekly reflection has been sent nor planned, it triggers the dialog.

fix: schedule weekly reflection when not automatically scheduled

---

Rasa_Bot/actions/actions_relapse_dialogs.py
Rasa_Bot/actions/actions_weekly_reflection.py

User got notifications after a dialog was ended for this particular dialog, which implied that the dialog hadn't been marked as completed. 'action_end_dialog' is deceptive as it doesn't really do anything right now, but mark_dialog_completed is important to conclude with so the State Machine updates the dialog as not running anymore.

Mark dialogs as completed after ending dialog

---

Rasa_Bot/data/rules/rules_notifications.yml

From what I am seeing, the tracking state notification is a daily notification triggered after the completion of the tracking dialog, and it's the only place after the onboarding where we don't send notifications to the user to ensure that they wear the watch and collect data. 
It seems as if adding this single line should do the trick, from what I've looked at, but I'm not completely sure, so I also wouldn't mind making a different notification to add to this state.

Adds the notification to tracking state

---

Rasa_Bot/actions/actions_goal_setting_dialog.py
Rasa_Bot/data/rules/rules_weekly_reflection_dialog.yml

Added the followupaction so we return to the right place, and added two rules so that rasa doesn't get confused.
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/493

return to weekly reflection successfully
